[package]
name = "uefi_loader"
version = "0.1.0"
authors = ["Dario Bartussek <d.bartussek@gmail.com>"]
edition = "2018"

[dependencies]
uefi = { version = "0.4.2", features = ['exts'] }
uefi-services = "0.2"

log = "0.4"
