[package]
name = "kernel_spin"
version = "0.1.0"
authors = ["Dario Bartussek <d.bartussek@gmail.com>"]
edition = "2018"

[dependencies]
spin = "0.5"

x86_64 = "0.9"

cpu_local_storage = { path = "../cpu_local_storage" }
