[package]
name = "kernel"
version = "0.1.0"
authors = ["Dario Bartussek <d.bartussek@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "crates/uefi/uefi_loader",
    "crates/kernel/core"
]

[dependencies]
structopt = "0.3"
