[package]
name = "page_management"
version = "0.1.0"
authors = ["Dario Bartussek <d.bartussek@gmail.com>"]
edition = "2018"

[dependencies]
x86_64 = "0.9"

log = "0.4"

spin = "0.5"

ffi_utils = { path = "../../ffi/ffi_utils" }

kernel_spin = { path = "../../kernel/kernel_spin" }
