[package]
name = "page_management"
version = "0.1.0"
authors = ["Dario Bartussek <d.bartussek@gmail.com>"]
edition = "2018"

[dependencies]
ffi_utils = { path = "../ffi_utils" }

x86_64 = "0.9"

spin = "0.5"

log = "0.4"
