[package]
name = "core"
version = "0.1.0"
authors = ["Dario Bartussek <d.bartussek@gmail.com>"]
edition = "2018"

[dependencies]
page_usage = { path = "../../ffi/page_usage" }
page_table = { path = "../../ffi/page_table" }

uefi = "0.4.2"

qemu-exit = "0.1"
